# Generated by Django 6.0.7 on 2026-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Designing', 'Designing'), ('Languages', 'Languages'), ('Photography', 'Photography'), ('Music', 'Music'), ('Marketing', 'Marketing'), ('Academics', 'Academics')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
