# Generated by Django 6.0.7 on 2026-09-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('teach', 'Can Teach'), ('learn', 'Want to Learn')], max_length=10)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.studentprofile')),
            ],
        ),
    ]
